import type { Restaurant, FoodListing, ImpactMetrics } from "./types"

export const mockRestaurants: Restaurant[] = [
  {
    id: "rest-1",
    name: "Green Leaf Bistro",
    address: "123 Eco Street, San Francisco, CA",
    phone: "(415) 555-0123",
    email: "contact@greenleaf.com",
    description: "Organic farm-to-table restaurant committed to zero waste",
    image: "/modern-organic-restaurant-interior.jpg",
    rating: 4.8,
    ownerId: "user-1",
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "rest-2",
    name: "Savory Kitchen",
    address: "456 Main Ave, San Francisco, CA",
    phone: "(415) 555-0456",
    email: "hello@savorykitchen.com",
    description: "Contemporary cuisine with sustainable practices",
    image: "/contemporary-restaurant-kitchen.jpg",
    rating: 4.6,
    ownerId: "user-2",
    createdAt: new Date("2024-02-20"),
  },
  {
    id: "rest-3",
    name: "Ocean Breeze Cafe",
    address: "789 Beach Blvd, San Francisco, CA",
    phone: "(415) 555-0789",
    email: "info@oceanbreeze.com",
    description: "Fresh seafood and coastal flavors with eco-friendly operations",
    image: "/coastal-cafe-with-ocean-view.jpg",
    rating: 4.7,
    ownerId: "user-3",
    createdAt: new Date("2024-03-10"),
  },
]

export const mockListings: FoodListing[] = [
  {
    id: "listing-1",
    restaurantId: "rest-1",
    title: "Fresh Garden Salad Bowl",
    description: "Mixed greens with seasonal vegetables, house vinaigrette",
    originalPrice: 12.99,
    discountedPrice: 4.99,
    discount: 62,
    quantity: 5,
    availableUntil: new Date(Date.now() + 2 * 60 * 60 * 1000),
    category: "Salads",
    image: "/fresh-garden-salad-bowl.jpg",
    allergens: ["nuts"],
    dietaryInfo: ["vegetarian", "vegan", "gluten-free"],
    cookedAt: new Date(Date.now() - 1 * 60 * 60 * 1000),
    expiryTime: new Date(Date.now() + 3 * 60 * 60 * 1000),
    pickupInstructions: "Show OTP at counter. Collect from the takeout section on the left.",
    createdAt: new Date(),
  },
  {
    id: "listing-2",
    restaurantId: "rest-1",
    title: "Artisan Sourdough Bread",
    description: "Freshly baked this morning, perfect for sandwiches or toast",
    originalPrice: 8.0,
    discountedPrice: 3.0,
    discount: 63,
    quantity: 8,
    availableUntil: new Date(Date.now() + 3 * 60 * 60 * 1000),
    category: "Bakery",
    image: "/artisan-sourdough-loaf.png",
    allergens: ["gluten"],
    dietaryInfo: ["vegetarian"],
    cookedAt: new Date(Date.now() - 4 * 60 * 60 * 1000),
    expiryTime: new Date(Date.now() + 8 * 60 * 60 * 1000),
    pickupInstructions: "Available at the bakery counter. Please bring your own bag!",
    createdAt: new Date(),
  },
  {
    id: "listing-3",
    restaurantId: "rest-2",
    title: "Grilled Chicken Wrap",
    description: "Herb-marinated chicken with fresh vegetables in a whole wheat wrap",
    originalPrice: 14.99,
    discountedPrice: 5.99,
    discount: 60,
    quantity: 6,
    availableUntil: new Date(Date.now() + 1.5 * 60 * 60 * 1000),
    category: "Sandwiches",
    image: "/grilled-chicken-wrap-sandwich.jpg",
    allergens: ["gluten", "dairy"],
    dietaryInfo: [],
    cookedAt: new Date(Date.now() - 0.5 * 60 * 60 * 1000),
    expiryTime: new Date(Date.now() + 2 * 60 * 60 * 1000),
    pickupInstructions: "Pick up from the main counter. Show confirmation code.",
    createdAt: new Date(),
  },
  {
    id: "listing-4",
    restaurantId: "rest-2",
    title: "Pasta Primavera",
    description: "Fresh pasta with seasonal vegetables in light olive oil",
    originalPrice: 16.99,
    discountedPrice: 6.99,
    discount: 59,
    quantity: 4,
    availableUntil: new Date(Date.now() + 2.5 * 60 * 60 * 1000),
    category: "Main Course",
    image: "/pasta-primavera.png",
    allergens: ["gluten"],
    dietaryInfo: ["vegetarian"],
    cookedAt: new Date(Date.now() - 1.5 * 60 * 60 * 1000),
    expiryTime: new Date(Date.now() + 4 * 60 * 60 * 1000),
    pickupInstructions: "Mention ReBite order at the front desk.",
    createdAt: new Date(),
  },
  {
    id: "listing-5",
    restaurantId: "rest-3",
    title: "Grilled Salmon Plate",
    description: "Wild-caught salmon with roasted vegetables and quinoa",
    originalPrice: 22.99,
    discountedPrice: 9.99,
    discount: 57,
    quantity: 3,
    availableUntil: new Date(Date.now() + 1 * 60 * 60 * 1000),
    category: "Seafood",
    image: "/grilled-salmon-with-vegetables.jpg",
    allergens: ["fish"],
    dietaryInfo: ["gluten-free"],
    cookedAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
    expiryTime: new Date(Date.now() + 2 * 60 * 60 * 1000),
    pickupInstructions: "Available at the bar area. Ask for to-go orders.",
    createdAt: new Date(),
  },
  {
    id: "listing-6",
    restaurantId: "rest-3",
    title: "Berry Cheesecake Slice",
    description: "Creamy New York style cheesecake with mixed berries",
    originalPrice: 7.99,
    discountedPrice: 3.49,
    discount: 56,
    quantity: 10,
    availableUntil: new Date(Date.now() + 4 * 60 * 60 * 1000),
    category: "Desserts",
    image: "/berry-cheesecake-slice.jpg",
    allergens: ["dairy", "eggs", "gluten"],
    dietaryInfo: ["vegetarian"],
    cookedAt: new Date(Date.now() - 3 * 60 * 60 * 1000),
    expiryTime: new Date(Date.now() + 6 * 60 * 60 * 1000),
    pickupInstructions: "Desserts available at the pastry display near entrance.",
    createdAt: new Date(),
  },
]

export const mockImpactMetrics: ImpactMetrics = {
  totalMealsSaved: 1247,
  co2Saved: 3741, // kg
  moneySaved: 18705,
  wasteReduced: 935, // kg
}
