import type {
  Restaurant,
  FoodListing,
  ImpactMetrics,
  UserProfile,
  Badge,
  LoyaltyTier,
  SubscriptionPlan,
  CharityCampaign,
  Activity,
} from "./types"

export const mockRestaurants: Restaurant[] = [
  {
    id: "rest-1",
    name: "Green Leaf Bistro",
    address: "123 Eco Street, San Francisco, CA",
    phone: "(415) 555-0123",
    email: "contact@greenleaf.com",
    description: "Organic farm-to-table restaurant committed to zero waste",
    image: "/modern-organic-restaurant-interior.jpg",
    rating: 4.8,
    ownerId: "user-1",
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "rest-2",
    name: "Savory Kitchen",
    address: "456 Main Ave, San Francisco, CA",
    phone: "(415) 555-0456",
    email: "hello@savorykitchen.com",
    description: "Contemporary cuisine with sustainable practices",
    image: "/contemporary-restaurant-kitchen.jpg",
    rating: 4.6,
    ownerId: "user-2",
    createdAt: new Date("2024-02-20"),
  },
  {
    id: "rest-3",
    name: "Ocean Breeze Cafe",
    address: "789 Beach Blvd, San Francisco, CA",
    phone: "(415) 555-0789",
    email: "info@oceanbreeze.com",
    description: "Fresh seafood and coastal flavors with eco-friendly operations",
    image: "/coastal-cafe-with-ocean-view.jpg",
    rating: 4.7,
    ownerId: "user-3",
    createdAt: new Date("2024-03-10"),
  },
]

export const mockListings: FoodListing[] = [
  {
    id: "listing-1",
    restaurantId: "rest-1",
    title: "Fresh Garden Salad Bowl",
    description: "Mixed greens with seasonal vegetables, house vinaigrette",
    originalPrice: 12.99,
    discountedPrice: 4.99,
    discount: 62,
    quantity: 5,
    availableUntil: new Date(Date.now() + 2 * 60 * 60 * 1000),
    category: "Salads",
    image: "/fresh-garden-salad-bowl.jpg",
    allergens: ["nuts"],
    dietaryInfo: ["vegetarian", "vegan", "gluten-free"],
    cookedAt: new Date(Date.now() - 1 * 60 * 60 * 1000),
    expiryTime: new Date(Date.now() + 3 * 60 * 60 * 1000),
    pickupInstructions: "Show OTP at counter. Collect from the takeout section on the left.",
    createdAt: new Date(),
  },
  {
    id: "listing-2",
    restaurantId: "rest-1",
    title: "Artisan Sourdough Bread",
    description: "Freshly baked this morning, perfect for sandwiches or toast",
    originalPrice: 8.0,
    discountedPrice: 3.0,
    discount: 63,
    quantity: 8,
    availableUntil: new Date(Date.now() + 3 * 60 * 60 * 1000),
    category: "Bakery",
    image: "/artisan-sourdough-loaf.png",
    allergens: ["gluten"],
    dietaryInfo: ["vegetarian"],
    cookedAt: new Date(Date.now() - 4 * 60 * 60 * 1000),
    expiryTime: new Date(Date.now() + 8 * 60 * 60 * 1000),
    pickupInstructions: "Available at the bakery counter. Please bring your own bag!",
    createdAt: new Date(),
  },
  {
    id: "listing-3",
    restaurantId: "rest-2",
    title: "Grilled Chicken Wrap",
    description: "Herb-marinated chicken with fresh vegetables in a whole wheat wrap",
    originalPrice: 14.99,
    discountedPrice: 5.99,
    discount: 60,
    quantity: 6,
    availableUntil: new Date(Date.now() + 1.5 * 60 * 60 * 1000),
    category: "Sandwiches",
    image: "/grilled-chicken-wrap-sandwich.jpg",
    allergens: ["gluten", "dairy"],
    dietaryInfo: [],
    cookedAt: new Date(Date.now() - 0.5 * 60 * 60 * 1000),
    expiryTime: new Date(Date.now() + 2 * 60 * 60 * 1000),
    pickupInstructions: "Pick up from the main counter. Show confirmation code.",
    createdAt: new Date(),
  },
  {
    id: "listing-4",
    restaurantId: "rest-2",
    title: "Pasta Primavera",
    description: "Fresh pasta with seasonal vegetables in light olive oil",
    originalPrice: 16.99,
    discountedPrice: 6.99,
    discount: 59,
    quantity: 4,
    availableUntil: new Date(Date.now() + 2.5 * 60 * 60 * 1000),
    category: "Main Course",
    image: "/pasta-primavera.png",
    allergens: ["gluten"],
    dietaryInfo: ["vegetarian"],
    cookedAt: new Date(Date.now() - 1.5 * 60 * 60 * 1000),
    expiryTime: new Date(Date.now() + 4 * 60 * 60 * 1000),
    pickupInstructions: "Mention ReBite order at the front desk.",
    createdAt: new Date(),
  },
  {
    id: "listing-5",
    restaurantId: "rest-3",
    title: "Grilled Salmon Plate",
    description: "Wild-caught salmon with roasted vegetables and quinoa",
    originalPrice: 22.99,
    discountedPrice: 9.99,
    discount: 57,
    quantity: 3,
    availableUntil: new Date(Date.now() + 1 * 60 * 60 * 1000),
    category: "Seafood",
    image: "/grilled-salmon-with-vegetables.jpg",
    allergens: ["fish"],
    dietaryInfo: ["gluten-free"],
    cookedAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
    expiryTime: new Date(Date.now() + 2 * 60 * 60 * 1000),
    pickupInstructions: "Available at the bar area. Ask for to-go orders.",
    createdAt: new Date(),
  },
  {
    id: "listing-6",
    restaurantId: "rest-3",
    title: "Berry Cheesecake Slice",
    description: "Creamy New York style cheesecake with mixed berries",
    originalPrice: 7.99,
    discountedPrice: 3.49,
    discount: 56,
    quantity: 10,
    availableUntil: new Date(Date.now() + 4 * 60 * 60 * 1000),
    category: "Desserts",
    image: "/berry-cheesecake-slice.jpg",
    allergens: ["dairy", "eggs", "gluten"],
    dietaryInfo: ["vegetarian"],
    cookedAt: new Date(Date.now() - 3 * 60 * 60 * 1000),
    expiryTime: new Date(Date.now() + 6 * 60 * 60 * 1000),
    pickupInstructions: "Desserts available at the pastry display near entrance.",
    createdAt: new Date(),
  },
]

export const mockImpactMetrics: ImpactMetrics = {
  totalMealsSaved: 1247,
  co2Saved: 3741, // kg
  moneySaved: 18705,
  wasteReduced: 935, // kg
}

// User Profiles
export const mockUserProfiles: UserProfile[] = [
  {
    id: "profile-1",
    userId: "user-consumer",
    bio: "Passionate about reducing food waste and living sustainably 🌱",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=consumer1",
    location: "San Francisco, CA",
    dietaryPreferences: ["vegetarian", "gluten-free"],
    followers: ["user-2", "user-3"],
    following: ["user-1", "user-2"],
    joinedAt: new Date("2024-01-15"),
  },
  {
    id: "profile-2",
    userId: "user-1",
    bio: "Food enthusiast committed to sustainability",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=user1",
    location: "Oakland, CA",
    dietaryPreferences: ["vegan"],
    followers: ["user-consumer"],
    following: [],
    joinedAt: new Date("2023-12-01"),
  },
]

// Badges & Achievements
export const mockBadges: Badge[] = [
  {
    id: "badge-1",
    name: "First Meal Saver",
    description: "Purchased your first ReBite meal",
    icon: "🥳",
    criteria: "Complete 1 purchase",
  },
  {
    id: "badge-2",
    name: "Waste Warrior",
    description: "Saved 10 meals from waste",
    icon: "⚔️",
    criteria: "Save 10 meals",
  },
  {
    id: "badge-3",
    name: "Carbon Crusader",
    description: "Prevented 50kg of CO2 emissions",
    icon: "🌍",
    criteria: "Prevent 50kg CO2",
  },
  {
    id: "badge-4",
    name: "Recipe Master",
    description: "Generated 5 AI recipes",
    icon: "👨‍🍳",
    criteria: "Create 5 recipes",
  },
  {
    id: "badge-5",
    name: "Streak Star",
    description: "Maintained a 7-day streak",
    icon: "⭐",
    criteria: "7-day streak",
  },
  {
    id: "badge-6",
    name: "Community Leader",
    description: "Gained 50 followers",
    icon: "👑",
    criteria: "50 followers",
  },
]

// Loyalty Tiers
export const mockLoyaltyTiers: LoyaltyTier[] = [
  {
    name: "bronze",
    minPoints: 0,
    benefits: ["Earn 1 point per dollar spent", "Access to community features"],
    discountPercentage: 0,
  },
  {
    name: "silver",
    minPoints: 500,
    benefits: ["Earn 1.5 points per dollar", "5% extra discount on purchases", "Early access to deals"],
    discountPercentage: 5,
  },
  {
    name: "gold",
    minPoints: 1500,
    benefits: ["Earn 2 points per dollar", "10% extra discount", "VIP customer support", "$5 monthly credit"],
    discountPercentage: 10,
  },
  {
    name: "platinum",
    minPoints: 3000,
    benefits: ["Earn 3 points per dollar", "15% extra discount", "Exclusive events", "$15 monthly credit", "Personal concierge"],
    discountPercentage: 15,
  },
]

// Subscription Plans
export const mockSubscriptionPlans: SubscriptionPlan[] = [
  {
    id: "free",
    name: "Free",
    price: 0,
    billingPeriod: "monthly",
    features: [
      { name: "Basic Marketplace", description: "Browse and purchase surplus food", included: true },
      { name: "AI Recipe Generator", description: "Generate recipes from ingredients", included: true },
      { name: "Impact Tracking", description: "Track your environmental impact", included: true },
      { name: "Community Features", description: "Follow users and view activity", included: false },
      { name: "Early Deal Access", description: "2-hour early access to deals", included: false },
      { name: "Free Delivery Credits", description: "$20/month delivery credit", included: false },
      { name: "Ad-free Experience", description: "Browse without ads", included: false },
    ],
    benefits: [
      "Access to all basic features",
      "Browse marketplace and create accounts",
      "Generate AI recipes",
      "Track personal impact",
    ],
  },
  {
    id: "pro",
    name: "Pro",
    price: 9.99,
    billingPeriod: "monthly",
    features: [
      { name: "Basic Marketplace", description: "Browse and purchase surplus food", included: true },
      { name: "AI Recipe Generator", description: "Generate recipes from ingredients", included: true },
      { name: "Impact Tracking", description: "Track your environmental impact", included: true },
      { name: "Community Features", description: "Follow users and view activity", included: true },
      { name: "Early Deal Access", description: "2-hour early access to deals", included: true },
      { name: "Free Delivery Credits", description: "$20/month delivery credit", included: false },
      { name: "Ad-free Experience", description: "Browse without ads", included: true },
    ],
    benefits: [
      "All Basic features",
      "10% extra discount on all purchases",
      "2-hour early access to deals",
      "Ad-free experience",
      "Priority customer support",
    ],
  },
  {
    id: "premium",
    name: "Premium",
    price: 19.99,
    billingPeriod: "monthly",
    features: [
      { name: "Basic Marketplace", description: "Browse and purchase surplus food", included: true },
      { name: "AI Recipe Generator", description: "Generate recipes from ingredients", included: true },
      { name: "Impact Tracking", description: "Track your environmental impact", included: true },
      { name: "Community Features", description: "Follow users and view activity", included: true },
      { name: "Early Deal Access", description: "2-hour early access to deals", included: true },
      { name: "Free Delivery Credits", description: "$20/month delivery credit", included: true },
      { name: "Ad-free Experience", description: "Browse without ads", included: true },
    ],
    benefits: [
      "All Pro features",
      "$20/month delivery credit",
      "Free shipping on qualifying orders",
      "Exclusive restaurant partnerships",
      "Nutrition coaching access",
      "VIP status at partner restaurants",
    ],
  },
  {
    id: "business",
    name: "Business",
    price: 99,
    billingPeriod: "monthly",
    features: [
      { name: "Advanced Analytics", description: "Real-time sales and performance data", included: true },
      { name: "Demand Forecasting", description: "AI-powered demand predictions", included: true },
      { name: "Marketing Tools", description: "Campaign creation and ROI tracking", included: true },
      { name: "Multi-Location Support", description: "Manage multiple restaurants", included: true },
      { name: "Staff Management", description: "Role-based access control", included: true },
      { name: "API Access", description: "Custom integrations", included: true },
      { name: "Dedicated Support", description: "Priority support & account manager", included: true },
    ],
    benefits: [
      "For restaurants",
      "Advanced analytics and reporting",
      "AI demand forecasting",
      "Marketing campaign tools",
      "Multi-location management",
      "Dedicated account manager",
    ],
  },
]

// Charity Campaigns
export const mockCharityCampaigns: CharityCampaign[] = [
  {
    id: "campaign-1",
    title: "Feed Local Food Bank",
    description: "Help us donate surplus food to the local food bank and support families in need",
    targetAmount: 5000,
    currentAmount: 3240,
    beneficiary: "San Francisco Food Bank",
    endDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
  },
  {
    id: "campaign-2",
    title: "Ocean Cleanup Initiative",
    description: "Support ocean cleanup efforts while reducing food waste from coastal restaurants",
    targetAmount: 10000,
    currentAmount: 7850,
    beneficiary: "Ocean Conservancy",
    endDate: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000),
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000),
  },
]

// Activity Feed
export const mockActivities: Activity[] = [
  {
    id: "activity-1",
    userId: "user-1",
    userName: "Sarah Chen",
    userAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=sarah",
    type: "purchase",
    description: "purchased Fresh Garden Salad Bowl from Green Leaf Bistro",
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
  },
  {
    id: "activity-2",
    userId: "user-2",
    userName: "Marcus Johnson",
    userAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=marcus",
    type: "achievement",
    description: "unlocked Waste Warrior badge - saved 10 meals",
    timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000),
  },
  {
    id: "activity-3",
    userId: "user-3",
    userName: "Elena Rodriguez",
    userAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=elena",
    type: "review",
    description: "left a 5-star review for Ocean Breeze Cafe",
    timestamp: new Date(Date.now() - 8 * 60 * 60 * 1000),
  },
  {
    id: "activity-4",
    userId: "user-consumer",
    userName: "You",
    userAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=you",
    type: "follow",
    description: "started following Green Leaf Bistro",
    timestamp: new Date(Date.now() - 12 * 60 * 60 * 1000),
  },
]
